detectors:
  RuleDetector:
   method_type: rule_detector
   auto_config: false
   rules:
     - rule: "R001 - TemplateNotFound"
     - rule: "R003 - CheckForExceptions"
     - rule: "R004 - ErrorLevelFound"
