FROM fluent/fluentd:v1.19.3-2.2

USER root

RUN apt update -y && apt install -y make build-essential libnng-dev

RUN fluent-gem install fluent-plugin-parser-protobuf
RUN fluent-gem install fluent-plugin-detectmate
RUN fluent-gem install fluent-plugin-nng
RUN fluent-gem install fluent-plugin-kafka
