site_name: DetectMate Service
site_url: https://ait-detectmate.github.io/DetectMateService/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - User Guide:
    - Installation: installation.md
    - Configuration: configuration.md
    - Usage:
      - Running the Service: usage.md
      - Using a Library Component: library.md
      - Monitoring with Prometheus: prometheus.md
    - Docker Compose Reference: docker-compose.md
  - Contributing:
    - Git Workflow: contribution.md
    - Development:
      - Overview: development.md
      - Library Imports: library-imports.md
      - Interfaces: interfaces.md
  - Maintainers:
    - Release Process: release.md



markdown_extensions:
  - admonition
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences
