component_name: NewValueDetector01
component_type: NewValueDetector  # this is the component class name, the service will automatically search for the matching component config schema
log_level: "DEBUG"
log_dir: "/logs"

# Manager Interface (Command Channel)
http_host: 0.0.0.0

# Engine Interface (Data Channel)
engine_addr: "ipc:///run/detector.ipc"
engine_autostart: true

# Output Destinations (where processed data is sent)
out_addr:
  - "ipc:///run/output.ipc"

out_dial_timeout: 1000
